export const privacyPolicyContent = `
  <header class="hash-privacy-header"><div class="container hash-privacy-header-inner"><a class="brand" href="./index.html#top" title="Go to home"><span class="brand-mark"><span></span><span></span><span></span></span><span>NEXTGEN<span class="brand-accent">ITSOLUTION</span></span></a><a class="hash-home-link" href="./index.html#top">Back to home</a></div></header>
  <div class="container legal-card hash-legal-card">
    <div class="section-kicker"><span>LEGAL</span><span class="kicker-rule"></span><span>YOUR PRIVACY</span></div>
    <h1>Privacy <em>Policy</em></h1>
    <p class="legal-intro"><strong>Last Updated: September 14, 2026</strong><br><br>Welcome to nextgenitsolution ("we," "our," or "us"). We respect your privacy and are committed to protecting the personal information of visitors and users of our website, nextgenitsolution.co.in.</p>
    <p class="legal-intro">This Privacy Policy explains how we collect, use, protect, and handle your information when you visit our website or use our IT services.</p>
    <div class="legal-policy">
      <section class="legal-section"><h2>1. Information We Collect</h2><p>We may collect personal information that you voluntarily provide to us, including:</p><ul><li>Name</li><li>Email address</li><li>Phone number</li><li>Company or business information</li><li>Information submitted through contact forms</li><li>Any other information you provide when contacting us</li><li>Reply "STOP" to opt out</li></ul><p>We may also automatically collect certain non-personal information when you visit our website, such as:</p><ul><li>IP address</li><li>Browser type</li><li>Device information</li><li>Pages visited</li><li>Date and time of your visit</li><li>Website usage information</li></ul></section>
      <section class="legal-section"><h2>2. How We Use Your Information</h2><p>We may use your information to:</p><ul><li>Respond to your inquiries and requests</li><li>Provide IT solutions and related services</li><li>Communicate with you about our services</li><li>Improve our website and user experience</li><li>Analyze website usage and performance</li><li>Maintain the security of our website</li><li>Comply with applicable legal requirements</li></ul></section>
      <section class="legal-section"><h2>3. How We Protect Your Information</h2><p>We take reasonable administrative, technical, and security measures to protect your personal information against unauthorized access, alteration, disclosure, or destruction.</p><p>However, please understand that no method of transmission over the internet or electronic storage is completely secure. While we strive to protect your information, we cannot guarantee absolute security.</p></section>
      <section class="legal-section"><h2>4. Sharing of Information</h2><p>We do not sell, rent, or trade your personal information to third parties.</p><p>We may share information only when necessary with trusted service providers who help us operate our website or provide our services, or when required by law.</p></section>
      <section class="legal-section"><h2>5. Cookies and Website Analytics</h2><p>Our website may use cookies and similar technologies to improve your browsing experience and understand how visitors use our website.</p><p>Cookies may help us:</p><ul><li>Understand website traffic</li><li>Improve website functionality</li><li>Analyze visitor interactions</li><li>Enhance user experience</li></ul><p>You can choose to disable cookies through your browser settings. However, some features of our website may not function properly if cookies are disabled.</p></section>
      <section class="legal-section"><h2>6. Third-Party Links</h2><p>Our website may contain links to third-party websites or services. We are not responsible for the privacy practices, content, or security of those third-party websites.</p><p>We encourage you to review the privacy policies of any third-party websites you visit.</p></section>
      <section class="legal-section"><h2>7. Your Privacy Rights</h2><p>Depending on your location and applicable laws, you may have the right to:</p><ul><li>Request access to your personal information</li><li>Request correction of inaccurate information</li><li>Request deletion of your personal information</li><li>Withdraw consent where applicable</li><li>Ask questions about how your information is collected and used</li></ul><p>To make a privacy-related request, please contact us using the information below.</p></section>
      <section class="legal-section"><h2>8. Children's Privacy</h2><p>Our website and services are not intended for children under the age of 13. We do not knowingly collect personal information from children.</p><p>If you believe that a child has provided us with personal information, please contact us, and we will take appropriate steps to remove the information.</p></section>
      <section class="legal-section"><h2>9. Changes to This Privacy Policy</h2><p>We may update this Privacy Policy from time to time. Any changes will be posted on this page along with an updated revision date.</p><p>We encourage you to review this Privacy Policy periodically.</p></section>
      <section class="legal-section"><h2>10. Contact Us</h2><p>If you have any questions, concerns, or requests regarding this Privacy Policy or your personal information, please contact us:</p><div class="legal-contact"><strong>nextgenitsolution</strong><span>Website: nextgenitsolution.co.in</span><span>Email: Cyber558278@gmail.com</span><span>Phone: +1 925-158-8467</span><span>Address: 160 Atherton DR<br>Exton, PA 19341<br>United States</span></div></section>
    </div>
    <a class="underlined-link" href="#top">Back to home <svg width="16" height="16"><use href="#icon-arrow"/></svg></a>
  </div>`;
